### ISSUE TITLE
Add an admin section in readme

### ISSUE THREAD

**Issue by rsrkpatwari1234** [rsrkpatwari1234/EchoForMe#15]
Make a small section above contributors table on the readme page with 'Project Admins' and add only @rsrkpatwari1234 and @vidit624 to it

**Comment by imakash3011** [comment]
I would like to work on this issue.

**Comment by rsrkpatwari1234** [comment]
Ok @imakash3011 , I will assign you the issue once the coding phase of JWOC starts

**Comment by imakash3011** [comment]
@rsrkpatwari1234  okay no problem.
