### ISSUE TITLE
Contributors Images

### ISSUE THREAD

**Issue by Swastik1710** [rsrkpatwari1234/EchoForMe#20]
## 📚 Documentation

Adding Contributors image in the readme file .

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/rsrkpatwari1234/EchoForMe/blob/main/CONTRIBUTING.md)?

Yes, I've read the contributing guidelines.

**Comment by Swastik1710** [comment]
As of now the Contributors list is not up to date.
I want to make it up to date ,
Can I please work on this issue ?

**Comment by vidit624** [comment]
@Swastik1710 go ahead!!

**Comment by Swastik1710** [comment]
Hey @vidit624 , I've made a PR regarding this issue.
Kindly review it and please do add the DWOC and Level labels to it.
