### ISSUE TITLE
The Issue Template has the wrong repo name in it.

### ISSUE THREAD

**Issue by vismitap** [rsrkpatwari1234/EchoForMe#24]
## 🐛 Bug Report

(A clear and concise description of what the bug is.)
Here, in the Proposal section, the name of the repo is socli which needs to be corrected.
![image](https://user-images.githubusercontent.com/47056243/107826137-5bfb5d00-6daa-11eb-917c-29e697b40530.png)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/rsrkpatwari1234/EchoForMe/blob/main/CONTRIBUTING.md)?
Yes

I would like to work on this as part of DWoC!

**Comment by noviicee** [comment]
I would like to fix the bug. Can you assign the task to me?

**Comment by rsrkpatwari1234** [comment]
I cannot assign such a minor change as a part of dwoc

**Comment by noviicee** [comment]
I just wanted to fix the bug, not as a part of dwoc
It's alright though. 👍
