### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Vrushti24** [rsrkpatwari1234/EchoForMe#26]
## 📚 Documentation

(A clear and concise description of what the issue is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/rsrkpatwari1234/EchoForMe/blob/main/CONTRIBUTING.md)?
It does not have any license it's important to have license so I can add MIT license for this project

**Comment by Vrushti24** [comment]
Please assign me this @rsrkpatwari1234

**Comment by rsrkpatwari1234** [comment]
not needed
