### ISSUE TITLE
Integrate Welcome and Greeting Bot 

### ISSUE THREAD

**Issue by akrish4** [rsrkpatwari1234/EchoForMe#9]
Hi @rsrkpatwari1234 

I would like to contribute to this amazing project
I can add a config file and integrate the bot so that whenever a new user opens a issue or pr , the bot will comment and greet the user with a proper message

Let me know if you are interested

Kindly do assign me
Kindly do add the DWOC and Level label

**Comment by rsrkpatwari1234** [comment]
@akrish4 go ahead !!

**Comment by akrish4** [comment]
Now you just have to install and configure the bot from github official site ie https://github.com/apps/welcome and select repository and rest all bot will do on its own since i added config file 
the bot are made by github only
